apiVersion: v1
kind: Secret
metadata:
  name: user-services-secret
  namespace: be-user
type: Opaque
stringData:
  DB_MONGO_USER: aW5pdXNlcm5hbWVjb3k=
  DB_MONGO_PASS: aW5pcGFzc3dvcmRjb29vb295eXl5
  SECRET_KEY: aW5pc2VjUmV0dHRLZXl5eXk=
