env:
  browser: true
  commonjs: true
  es2021: true
parserOptions:
  ecmaVersion: latest
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
