name: CI/CD for Mono Repo

on:
  push:
    tags:
      - "release-*"

jobs:
  build-push-and-update-manifest:
    runs-on: ubuntu-latest
    steps:
      # Checkout Code
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      # Layanan Order
      - name: Build & Push Order Service
        uses: docker/build-push-action@v5
        with:
          context: ./App/order-nodejs
          file: ./App/order-nodejs/Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/order-services-nodejs:${{ github.ref_name }}
          push: true

      - name: Update Order Services Deployment manifest
        run: |
          NEW_IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/order-services-nodejs:${{ github.ref_name }}"
          sed -i "s|image: .*|image: $NEW_IMAGE|" ./manifest/apps/order/deployment.yml
          git config --global user.email "annasikn@yahoo.com"
          git config --global user.name "nvlannasik"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/nvlannasik/devops-usecase.git
          git add ./manifest/apps/order/deployment.yml
          git commit -m "Update Order Services Deployment manifest"
          git push origin HEAD:master

      # Layanan Product
      - name: Build & Push Product Service
        uses: docker/build-push-action@v5
        with:
          context: ./App/product-nodejs
          file: ./App/product-nodejs/Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/product-services-nodejs:${{ github.ref_name }}
          push: true

      - name: Update Product Services Deployment manifest
        run: |
          NEW_IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/product-services-nodejs:${{ github.ref_name }}"
          sed -i "s|image: .*|image: $NEW_IMAGE|" ./manifest/apps/product/deployment.yml
          git config --global user.email "annasikn@yahoo.com"
          git config --global user.name "nvlannasik"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/nvlannasik/devops-usecase.git
          git add ./manifest/apps/product/deployment.yml
          git commit -m "Update Product Services Deployment manifest"
          git push origin HEAD:master

      # Layanan User
      - name: Build & Push User Service
        uses: docker/build-push-action@v5
        with:
          context: ./App/user-go
          file: ./App/user-go/Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/user-services-go:${{ github.ref_name }}
          push: true

      - name: Update User Services Deployment manifest
        run: |
          NEW_IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/user-services-go:${{ github.ref_name }}"
          sed -i "s|image: .*|image: $NEW_IMAGE|" ./manifest/apps/user/deployment.yml
          git config --global user.email "annasikn@yahoo.com"
          git config --global user.name "nvlannasik"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/nvlannasik/devops-usecase.git
          git add ./manifest/apps/user/deployment.yml
          git commit -m "Update User Services Deployment manifest"
          git push origin HEAD:master
