name: CI/CD for Mono Repo

on:
  push:
    tags:
      - "release-*"

jobs:
  build-and-update-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Git
        run: |
          git config --global user.email "bot-ci"
          git config --global user.name "bot-ci"

      - name: Build & Push Services and Update Manifest
        run: |
          SERVICES=("order" "product" "user")
          APP_PATHS=("./App/order-nodejs" "./App/product-nodejs" "./App/user-go")
          DOCKERFILES=("Dockerfile" "Dockerfile" "Dockerfile")
          MANIFESTS=("./manifest/apps/order/deployment.yml" "./manifest/apps/product/deployment.yml" "./manifest/apps/user/deployment.yml")

          for i in ${!SERVICES[*]}; do
            # Build and Push
            docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${SERVICES[i]}-services:${{ github.ref_name }} -f ${APP_PATHS[i]}/${DOCKERFILES[i]} ${APP_PATHS[i]}
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/${SERVICES[i]}-services:${{ github.ref_name }}
            
            # Update manifest
            NEW_IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/${SERVICES[i]}-services:${{ github.ref_name }}"
            sed -i "s|image: .*|image: $NEW_IMAGE|" ${MANIFESTS[i]}
            git add ${MANIFESTS[i]}
          done

          # Commit and push all manifest updates at once
          git commit -m "Update manifests for release ${{ github.ref_name }}"
          git push https://${{ secrets.GH_PAT }}@github.com/***/devops-usecase.git HEAD:main
